// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:custom_mapper_annotation/custom_mapper_annotation.dart';

part 'models.freezed.dart';
part 'models.g.dart';
part 'models.map.dart'; // Generated by custom_mapper

/// Domain model representing a user in the application.
///
/// This is the core business object that contains the user's information
/// as used throughout the application logic.
@freezed
sealed class User with _$User {
  const factory User({
    required String id,
    required String name,
    required String email,
    required int age,
    String? profileImageUrl,
    required DateTime createdAt,
    required List<String> tags,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}

/// Data transfer object for user data from API responses.
///
/// This class demonstrates how to use custom_mapper to generate
/// mapping methods between domain objects and DTOs. The @Mapper
/// annotation tells custom_mapper to generate both toDomain() and
/// toData() methods.
@freezed
@Mapper(domain: User, toDomain: true, toData: true)
sealed class UserDto with _$UserDto {
  const factory UserDto({
    required String id,
    required String name,
    required String email,

    /// Age with default value if null in source
    @DefaultIfNull(18) required int age,

    /// Optional profile image URL
    String? profileImageUrl,

    /// ISO string representation of creation date
    required String createdAtIso,

    /// Comma-separated string of tags
    required String tagsString,

    /// Internal processing flag - ignored during mapping
    @IgnoreField() @Default(false) bool isProcessed,
  }) = _UserDto;

  factory UserDto.fromJson(Map<String, dynamic> json) =>
      _$UserDtoFromJson(json);
}

/// Simple DTO that only maps to domain (one-way mapping).
///
/// This demonstrates using @Mapper with only toDomain enabled,
/// which generates only the toDomain() method.
@freezed
@Mapper(domain: User, toDomain: true, toData: false)
sealed class SimpleUserDto with _$SimpleUserDto {
  const factory SimpleUserDto({
    required String id,

    @DefaultIfNull('Unknown User') required String name,

    required String email,

    @DefaultIfNull(0) required int age,

    /// Internal fields ignored during mapping
    @IgnoreField() @Default('') String internalNotes,
  }) = _SimpleUserDto;

  factory SimpleUserDto.fromJson(Map<String, dynamic> json) =>
      _$SimpleUserDtoFromJson(json);
}
